### ISSUE TITLE
Regenerate HTML version of ESSGLOBAL

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/map-sse#2]
Currently the HTML "front page" is static, and not generated from the RDF. It should be, as it will be going out of sync...

https://vocabs.solidarityeconomy.coop/essglobal/V2a/html-content/essglobal.html

**Comment by wu-lee** [comment]
Having trouble finding any tools to do this... I can't see evidence of any tools being used to generate it in this repository. 

Other tools which might get there:
- raptor - we already use this, but actually it only generates a CSV dump of the triples.
- python rdf-to-html - having trouble getting this to work, seems to need Python2 libs, and my Python package wranging skills aren't the best
- SpecGen - https://github.com/specgen/specgen also based on python, and about five years since the last commit. Can't yet get it to work.

**Comment by wu-lee** [comment]
See also: https://web.archive.org/web/20151031172323/http://answers.semanticweb.com/questions/1087/generating-documentation-from-rdfs-andor-owl-vocabularies

**Comment by ColmMassey** [comment]
@ThomasDavisonsGit I'd recomment looking at  https://datafoodconsortium.gitbook.io/dfc-standard-documentation/

for what is probably the closest project I know to what we are doing? They may have some tools we could use to visualise and edit our schemas.

**Comment by ColmMassey** [comment]
At the meeting on Thursday we discussed defining a simpler rdf visualisation task with immediate use. Can you create a script which given a language, generates a simple html page which lists all our supported VESs (Vocabulary Encoding Scheme) and their respective terms listed by its label in the requested language? 

Like:

- Economic activities/Sectors
  - Agriculture and environment
  - Natural resources extraction
  - ...
- Modified Economic activities/Sectors
  - Arts, Media, Culture & Leisure
  - Campaigning, Activism & Advocacy
  - ...
- Economic Activities/Sectors (ICA - L2)
- ...

**Comment by ColmMassey** [comment]
Actually first step should be just a csv file with the same info VES Labels in the first row and then list the terms in each column.

**Comment by ColmMassey** [comment]
OBO project now needs a csv file listing Organisational Structure VES & Economic Activities/Sectors (Modified) VES

**Comment by ColmMassey** [comment]
This issue (https://github.com/SolidarityEconomyAssociation/open-data/issues/63) is not the same but might end up being addressed as a side effect.

**Comment by wu-lee** [comment]
Like this? (These are actually tab-delimited, for easier eyeball access, but should cut & paste into a spreadsheet in the same way as a CSV.)  The `term` column is the final part of the term URI. The `EN` column is the English version of the `prefLabel` property.

organisational-structure:
```
term	EN
OS10	Community group (formal or informal)
OS20	Not-for-profit organisation
OS30	Social enterprise
OS40	Charity
OS50	Company (Other)
OS60	Workers cooperative
OS70	Housing cooperative
OS80	Consumer/User coops
OS90	Producer cooperative
OS100	Multi-stakeholder cooperative
OS110	Secondary cooperative
OS115	Cooperative
OS120	Community Interest Company (CIC)
OS130	Community Benefit Society / Industrial and Provident Society (IPS)
OS140	Employee trust
OS150	Self-employed
OS160	Unincorporated
OS170	Mutual
OS180	National apex
OS190	National sectoral federation or union
OS200	Regional, state or provincial level federation or union
OS210	Cooperative group
OS220	Government agency/body
OS230	Supranational
OS240	Cooperative of cooperatives / mutuals
```

activities-modified:
```
term	EN
AM10	Arts, Media, Culture & Leisure
AM20	Campaigning, Activism & Advocacy
AM30	Community & Collective Spaces
AM40	Education
AM50	Energy
AM60	Food
AM70	Goods & Services
AM80	Health, Social Care & Wellbeing
AM90	Housing
AM100	Money & Finance
AM110	Nature, Conservation & Environment
AM120	Reduce, Reuse, Repair & Recycle
AM130	Agriculture
AM140	Industry
AM150	Utilities
AM160	Transport
```

Basic HTML-isations of this should be trivial.

**Comment by wu-lee** [comment]
See also full vocab localisations here: https://nextcloud.solidarityeconomy.coop/index.php/apps/onlyoffice/s/i8dNYqbmj7MXrax

**Comment by ColmMassey** [comment]
Coming together nicely.

**Comment by ColmMassey** [comment]
I wonder before tackling the full 
https://vocabs.solidarityeconomy.coop/essglobal/V2a/html-content/essglobal.html

should we start with the simpler html pages we generate like

https://prod.data.solidarityeconomy.coop/ica/35336.html
?

**Comment by wu-lee** [comment]
An update.

Tom and I looked at `dowl.rb` and managed to get it working (it's just bitrotted slightly). It works with it's own supplied example, but not with one of our vocabs (we used activities-ica.ttl), because `dowl` expects the graph to have an ontology property with a title (there isn't in ours.)

However, what it does is fairly straightforward: read in a bunch of triples, stick it together into a data structure, and pass that to a HTML template to be rendered.  This sticking-together can be fairly generic, but the rendering in `dowl` would need to be changed allow for our expectations of the vocab data.

So Tom is planning to try and alter it to consume our vocabs, and the result can be discussed.

Looking at the Ruby projects on the Rubygems website which use `RDF.rb` I found one called [`yowl`][1] - this turns out to be a newer fork of `dowl`. Unfortunately the author deleted/hid his GitHub repository for it, which implies it is no longer maintained either. (The last release was 2013 or so.)  The code is still accessible on Rubygems, however.

[1]: https://rubygems.org/gems/yowl

**Comment by wu-lee** [comment]
We should also investigate LODE, which is one of the options on [LOV][1] to display information about the vocabs there. The links don't work because the server seems offline, as are pretty much all of the alternative tools there.

Here's a paper describing LODE:

https://explore.dublincore.net/learning_resource/making-ontology-documentation-with-lode/

The main website seems to be: https://essepuntato.it/lode/

They don't make it very easy to find but there is a Github project for it here:

https://github.com/essepuntato/LODE

The code is in Java, and it looks relatively maintained, with commits up to 2021.

The output looks a but like the usual W3C documents - so possibly too technical for some audiences, and experiments with `dowl` are useful anyway.


[1]: https://lov.linkeddata.es

**Comment by wu-lee** [comment]
Found linked on the LODE website, this best-practices guide for publishing linked data vocabs looks worth studying:

https://www.w3.org/TR/swbp-vocab-pub/

**Comment by ColmMassey** [comment]
I wonder can we find a conference to attend?

**Comment by ColmMassey** [comment]
@lin-d-hop

**Comment by ColmMassey** [comment]
Just noting, there are some discussions relating to this ticket [here](https://element.digitalcommons.coop/#/room/#semantics:digitalcommons.coop)

**Comment by ColmMassey** [comment]
So I think once

 - [ ] all the information in the ttl is reflected in the html
 - [ ] the hyperlinks work
 - [ ] there is some sort of nesting of the first list of Concepts, using perhaps url hierarchy
 - [ ] footer text is added
 - [ ] we have a solution for TOC
 - [ ] Section 1: Introduction and Definitions - Where should this text live? 

We could close this ticket, but actually I think we are abusing this ticket and we should consider splitting them out into new ones.

**Comment by ColmMassey** [comment]
A lot of discussion of this issue has spilled into https://docs.google.com/document/d/1hBlD-0apFPmiqnX_uzpw-oN5OJTtZScOE1fVUX8sVK4/edit which is not public. We'll steer the discussions back to github or the #semantics:digitalcommons.coop matrix channel.

**Comment by wu-lee** [comment]
A general update is that @ThomasDavisonsGit 's reworking of DOWL into "Goth" is generating reasonable looking documentation. It has some hard-wired things which need to be configurable - for example it needs to be
- able to process an arbitrary file (or files) into an arbitrary output location
- to be installable as a gem, so it can be used in the map-sse project
- have some unused web assets / dependencies purged

There may be a few other small things, Tom and I were discussing this in person yesterday.

**Comment by ThomasDavisonsGit** [comment]
I was going to ask what needs to be done to close this ticket, and I see some points from Colm and from Nick above.
I suggest closing this ticket now and transferring any unresolved items to separate issues on my repository here: https://github.com/ThomasDavisonsGit/goth

Thoughts?

**Comment by wu-lee** [comment]
Agreed

**Comment by ColmMassey** [comment]
Let's close once the a new page hax replaced the old one and the outstanding items are in new tickets. Please @ me in new tickets.

**Comment by ThomasDavisonsGit** [comment]
Goth and its issues moved to here: https://github.com/DigitalCommons/goth

**Comment by ColmMassey** [comment]
We can close this as a new autogenerated docuement is now published to 
https://dev.vocabs.solidarityeconomy.coop/essglobal/2.1/html-content/essglobal.html

Nice. :-) Will create new tickets for the remaining small twaeks and bugs identified.
